apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: limbo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: limbo
    spec:
      health:
        disabled: false
        initialDelaySeconds: 30
        periodSeconds: 60
      sdkServer:
        logLevel: Info
        grpcPort: 9357
        httpPort: 9358
      ports:
        - name: default
          protocol: TCP
          containerPort: 25568
      template:
        metadata:
          labels:
            app: limbo
        spec:
          nodeSelector:
            limbo-spawn-only: "true"  # Ensures the fleet spawns only on labeled nodes
          containers:
            - name: limbo
              image: ghcr.io/thepotatodev/limbo:latest
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: "500m"
                  memory: "512Mi"
                limits:
                  cpu: "1"
          imagePullSecrets:
            - name: drs
