apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: limbo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: limbo
    spec:
      health:
        disabled: false
        initialDelaySeconds: 30
        periodSeconds: 60
      sdkServer:
        logLevel: Info
        grpcPort: 9357
        httpPort: 9358
      ports:
        - name: default
          protocol: TCP
          containerPort: 25568
      template:
        metadata:
          labels:
            app: limbo
        spec:
          containers:
            - name: limbo
              image: limbo:latest
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: "1"
                  memory: "1G"
                limits:
                  cpu: "1"