apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: oneblock-spawn
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oneblock-spawn
    spec:
      health:
        disabled: false
        initialDelaySeconds: 30
        periodSeconds: 60
      sdkServer:
        logLevel: Info
        grpcPort: 9357
        httpPort: 9358
      ports:
        - name: default
          protocol: TCP
          containerPort: 25567
      template:
        metadata:
          labels:
            app: oneblock-spawn
        spec:
          containers:
            - name: spawn
              image: spawn:latest
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: "500m"
                  memory: "1G"
                limits:
                  cpu: "1"

