apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: server
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  replicas: 2  # Ensures at least one active server and one buffer server
  template:
    metadata:
      labels:
        app: server
    spec:
      health:
        disabled: false
        initialDelaySeconds: 30
        periodSeconds: 60
      sdkServer:
        logLevel: Info
        grpcPort: 9357
        httpPort: 9358
      ports:
        - name: default
          protocol: TCP
          containerPort: 25566
      template:
        metadata:
          labels:
            app: server
        spec:
          nodeSelector:
            server-only: "true"  # Ensures servers only spawn on specific nodes
          containers:
            - name: server
              image: ghcr.io/thepotatodev/server:latest
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: "500m"
                  memory: "1G"
                limits:
                  cpu: "1"
          imagePullSecrets:
            - name: drs
---
apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: server-fleet-autoscaler
spec:
  fleetName: server
  policy:
    type: Buffer
    buffer:
      bufferSize: 1  # Ensures one extra server is always ready
      maxReplicas: 5  # Maximum scaling limit
  sync:
    type: FixedInterval
    fixedInterval:
      seconds: 60  # Scaling check every 60 seconds
